version: '3.7'
services:
        solr:
                image: solr:9.0.0
                container_name: solr
                ports:
                        - "8983:8983"
                environment:
                        - ZK_HOST=zoo:2181
                networks:
                        - solr
                volumes:
                        - ./solr:/var/solr
                depends_on:
                        - zoo
                restart: unless-stopped

        zoo:
                image: zookeeper:3.6.2
                container_name: zoo
                hostname: zoo
                ports:
                        - "2181:2181"
                        - "7001:7000"
                environment:
                        ZOO_MY_ID: 1
                        ZOO_SERVERS: server.1=zoo:2888:3888;2181
                        ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
                        ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
                networks:
                        - solr

networks:
        solr:
                
